[phases.setup]
aptPkgs = [
    "libnss3",
    "libatk-bridge2.0-0",
    "libdrm2",
    "libxkbcommon0",
    "libgbm1",
    "libxshmfence1",
    "libasound2",
    "libglib2.0-0",
    "libgtk-3-0",
    "libx11-xcb1",
    "libxcomposite1",
    "libxcursor1",
    "libxdamage1",
    "libxi6",
    "libxtst6",
    "libxrandr2",
    "libxss1",
    "libxt6",
    "libxcb1",
    "libxcb-shm0",
    "libxcb-xfixes0",
    "libxcb-shape0",
    "libxcb-randr0",
    "libxcb-icccm4",
    "libxcb-image0",
    "libxcb-keysyms1",
    "libxcb-util1",
    "libxcb-render-util0",
    "libpango-1.0-0",
    "libcairo2",
    "libpangoft2-1.0-0",
    "libpangocairo-1.0-0",
    "libgdk-pixbuf2.0-0",
    "libatspi2.0-0",
    "libdbus-1-3",
    "libexpat1",
    "libfontconfig1",
    "libfreetype6",
    "libglib2.0-0",
    "libgssapi-krb5-2",
    "libjpeg62",
    "libpng16-16",
    "libssl3",
    "libstdc++6",
    "libuuid1",
    "libx11-6",
    "libx11-xcb1",
    "libxcb1",
    "libxcomposite1",
    "libxcursor1",
    "libxdamage1",
    "libxi6",
    "libxinerama1",
    "libxkbcommon0",
    "libxrandr2",
    "libxrender1",
    "libxss1",
    "libxtst6",
    "libz3-4"
]